app/scripts/components/Explore/index.jsx
- New button _request data_ on the explore page opens a _Request Data modal_.
=> add request data button and modal on the explore page

app/scripts/components/Create/index.jsx, app/scripts/components/Dashboards/DashboardDetail.jsx, app/scripts/components/Dashboards/index.jsx, app/scripts/components/Explore/ExploreSidebar.jsx, app/scripts/components/Explore/MetadataList.jsx, app/scripts/components/FAQ/index.jsx, app/scripts/components/Home/index.jsx, app/scripts/components/Insights/index.jsx, app/scripts/components/Modal/WelcomeModal.jsx, app/scripts/components/Partnership/DataAccessibility.jsx, app/scripts/components/Partnership/EngagementWorkgroup.jsx, app/scripts/components/Partnership/PlatformWorkgroup.jsx, app/scripts/components/Partnership/index.jsx, app/scripts/components/Resources/index.jsx, app/scripts/components/SummaryCards/index.jsx, app/scripts/metadata.json
Hi @davidsingal, 
I did another pass through the site for copy editing and to address the tickets that weren't clear. Also I noticed that when you fixed the code style last time, there were a few spots on the Create page where link tags were broken onto new lines, removing the space after the link in the sentence. 
- Check for capitalization and punctuation
- Add Whats Next to FAQ
- Rename "from" to "source" on explore sidebar push to new line
- Rename "source" to "access" on dataset detail page
- Update text on workgroup pages
- Fix spaces on Create page
- Move static text below summary on dashboards
- New text for summary cards
- Rename Platform Development to Platform Workgroup, Data Accessibility to Data Workgroup
=> Text edits

app/scripts/components/Dashboards/DashboardDetail.jsx
Changes to the _dashboardDetail_ intro text: from _data.summary_ to _data.content_.
=> change the dashboard detail summary to content

app/scripts/components/Explore/ExploreLegend.jsx, app/scripts/components/Explore/ExploreMap.jsx, app/styles/components/_explore-legend.scss
- A new scss class in explore-legend styles called title.
- A new scss subclass in explore-legend styles called units.
Changes the legend title units to no text-transform.
=> fixed issue where legend units were always uppercased

app/scripts/actions/datasets.js, app/scripts/actions/exploremap.js
- More reliable way to get the original order of the layers when opening a shared map.
- URL state update after changing the dataset layers order.
=> sharing layers in initial order fix

app/scripts/actions/datasets.js
- Original way to get the order of the layers when sharing a map.
- Corrects the wrong order issue!
=> fixed sharing layers in order

package-lock.json, package.json
eslint didn't know about the aliases we have defined in webpack so it would raise `no-unresolved` errors.
With the module [`eslint-import-resolver-webpack`](https://www.npmjs.com/package/eslint-import-resolver-webpack), eslint can properly do its job. Its configuration was already present in `.eslintrc.json` so I guess we used to have this module but lost it along the way.
=> Prevent eslint from raising "no-unresolved" errors

app/scripts/components/Dataset/index.jsx, app/scripts/components/auth/auth.js, app/scripts/components/user/user.js, app/scripts/index.jsx, app/styles/components/_widget-editor.scss, package.json, yarn.lock
This PR lets the logged user create widgets in the API from the dataset page. It also switches to the v0.0.8 of the [widget editor](https://github.com/resource-watch/widget-editor).
When clicking on "Check my widgets", note that the redirection is not working on this repository because the URL points to the prep-manager app.
=> Create a widget from the dataset page

app/scripts/components/nexgddp-tool/tool-map/CompareMap.jsx
This PR fix the issue with the compare map. After moving the divider you couldn't pan again. I change the library
=> NexGDDP: enable pan after moving the divider

app/styles/components/_widget-editor.scss, package-lock.json, package.json
This PR updates the widget editor to v0.1.0 which fixes a major bug preventing the restoration of the map widgets.
Because the new version also scopes all its CSS classes, this PR contains updates to the styles overrides.
=> Editor: Update to v0.1.0

app/scripts/components/Tooltip/ShareNexgddpChartTooltip.jsx
This PR fixes a bug that prevented the user from saving the chart as a widget in the NexGDDP tool.
You can test the fix by opening the modal to save the chart. You shouldn't see any error in the console.
[Pivotal task (first sub-task)](https://www.pivotaltracker.com/story/show/154279052)
=> NexGDDP: fix a bug that prevented the user from saving the chart as a widget

app/scripts/components/App/index.jsx, app/scripts/components/Navigation/SocialNav.jsx, app/styles/components/_nav.scss
Amend social nav layout/spacing to align with designs:
*PR does not include updated Facebook icon.*
**dev**
**design**
=> Fix layout spacing of the social nav to align with designs

app/styles/components/_share-control.scss
Fix share control position on the explore map:
=> Fix explore share control position

app/scripts/actions/nexgddptool.js, app/scripts/components/nexgddp-tool/tool-chart/TimeseriesChart.jsx
This PR adds a tooltip to the widgets generated from the chart of the NexGDDP tool. Note that this tooltip is not (yet) shown in the tool but only in places where we use the `VegaChart` component from RW (for example in My Prep).
You can test this PR by creating a widget from the NexGDDP tool and going to My Prep then. You won't be able to see the tooltip if https://github.com/resource-watch/prep-manager/pull/31 is not merged.
=> NexGDDP: Add a tooltip to the generated widgets

app/scripts/components/nexgddp-tool/tool-chart/TimeseriesChart.jsx, app/scripts/selectors/nexgddptool.js
This PR contains an updated chart for the NexGDDP tool (Vega spec from @aagm).
</p>
The chart contains a legend, the values on the Y axis are transformed according to the dataset to have more user-friendly units and the yellow boxes are now fixed.
=> NexGDDP: Update the chart

app/scripts/components/nexgddp-tool/NexGDDPTool.jsx, app/scripts/components/nexgddp-tool/style.scss
This PR adds a small sentence below the map of the NexGDDP tool to indicate the user to add a marker to analyte a specific place.
</p>
[Pivotal task](https://www.pivotaltracker.com/story/show/154278363)
=> NexGDDP: Add a help text below the map

app/scripts/components/nexgddp-tool/tool-chart/TimeseriesChart.jsx
This PR replaces he yellow windows of the chart of the NexGDDP tool by vertical lines as requested by David G. and the date range that is displayed within the graph is reverted to 9 years.
</p>
=> NexGDDP: Replace the windows by vertical lines

app/scripts/components/map-vis/layer-manager/carto-layer.js
This PR fixes a bug that prevented the Explore map to show two Carto layers at once.
Essentially, a few lines of code were written to make sure that if we update an existing layer, the previous request would be cancelled. In practice, since the instance of the map component is maintained throughout the interaction with the map, the lines would permit loading only one Carto layer at a time, rejecting a `Promise.all` that would be later in charge of displaying those layers.
In order to test the changes, go to this page: `/explore?activeDatasets=011a2a6a-3bd5-4a8a-9dda-57775db4e604|1|true|0&activeDatasets=c53a195f-d5f0-4acc-b1be-b773420a6606|1|true|1&basemap=default&boundaries=false&filterQuery=&labels=none&lat=48.3416461723746&lng=-123.92578125000001&location=global&minZoom=3&tab=core_datase …
=> Fixed a bug that prevented showing two Carto layers at once

app/scripts/actions/nexgddptool.js
This PR changes the default date range of the NexGDDP tool. Previously the first one available, it is now the one that includes today's date.
To test, go to `/dataset/tasmax_rcp45_decadal` and you should see "2011-2020" as the selected range.
[Pivotal task](https://www.pivotaltracker.com/story/show/154661044)
=> NexGDDP: change the default date range

app/scripts/services/dataset-filter-service.js
This PR recursively sorts the filters of the Explore Page.
To test it:
1. Open the Explore page
2. Click "All datasets"
3. Click "Filter results"
4. Click on any of the filters (for example, "Topics") and you'll see the whole tree is sorted instead of just the first level
[Pivotal task](https://www.pivotaltracker.com/story/show/154726972)
=> Correctly sort the filters of Explore

app/scripts/components/Tooltip/ShareNexgddpChartTooltip.jsx, app/scripts/components/nexgddp-tool/tool-map/CompareMap.jsx, app/scripts/components/nexgddp-tool/tool-map/DifferenceMap.jsx, app/scripts/components/nexgddp-tool/tool-map/SimpleMap.jsx, app/scripts/components/nexgddp-tool/tool-map/ToggleMap.jsx, app/scripts/components/share-control/share-control-component.jsx, app/scripts/pages/explore/explore-map/explore-map-component.jsx
This PR fixes two regressions that broke the ability to share the map and graph of the NexGDDP tool.
Go to any NexGDDP dataset to test it.
[Pivotal task](https://www.pivotaltracker.com/story/show/154805635)
=> NexGDDP: regressions that broke sharing the map and graph

app/scripts/components/nexgddp-tool/tool-chart/TimeseriesChart.jsx, app/scripts/components/nexgddp-tool/tool-chart/style.scss, package-lock.json, package.json
This PR adds a tooltip to the NexGDDP graph.
Previously, [I've already added a tooltip](https://github.com/resource-watch/prep-app/pull/179) to the configuration of the Vega spec, but it was only supported by other renderers (in My Prep for example). This PR tweaks the tooltip according to some feedback from WRI (see Pivotal's task) but also uses the [editor's renderer](https://github.com/resource-watch/widget-editor/blob/develop/src/components/chart/VegaChart.js) for the NexGDDP chart so the tooltip can be seen there too.
~~**🚨 This PR can't be merged until v0.1.2 of the [editor](https://github.com/resource-watch/widget-editor) is released because the latest version contains bugs in the renderer.**~~
This PR updates the [widget-editor](https://github.com/resource-watch/widget-editor) to …
=> NexGDDP: tooltip for the graph

app/scripts/components/nexgddp-tool/tool-chart/style.scss
This PR prevents the close button from overlapping the text labels of the chart.
Before the fix:
After:
[Comment on Pivotal](https://www.pivotaltracker.com/story/show/154409316/comments/185485944)
=> NexGDDP: prevent the close button from overlapping the chart

app/scripts/components/legend/legend-types/legend-gradient/LegendGradient.jsx, app/scripts/components/legend/legend-types/legend-gradient/legend-gradient.scss
This PR adds:
- Transparent step to gradient legends.
https://www.pivotaltracker.com/story/show/154842270
### Testing instructions ###
http://localhost:3000/explore?activeDatasets=aaadd6c3-93ea-44bc-ba8b-7af3f40d39e1%7C1%7Ctrue%7C1&activeDatasets=df0aabe8-0ef2-4a81-bdba-c6fc6767fde9%7C1%7Ctrue%7C0&basemap=default&bbox&boundaries=true&filterQuery=&labels=none&lat=50.12057809796008&lng=8.173828125000002&location=global&minZoom=3&tab=core_datasets&zoom=5
=> Gradient transparent legend

app/scripts/components/Modal/CreateEmbedWidget.jsx, app/scripts/components/Tooltip/ShareNexgddpChartTooltip.jsx, app/scripts/components/Tooltip/ShareNexgddpTooltip.jsx, app/scripts/components/nexgddp-tool/tool-chart/TimeseriesChart.jsx, app/scripts/components/nexgddp-tool/tool-map/CompareMap.jsx, app/scripts/components/nexgddp-tool/tool-map/DifferenceMap.jsx, app/scripts/components/nexgddp-tool/tool-map/SimpleMap.jsx, app/scripts/components/nexgddp-tool/tool-map/ToggleMap.jsx, app/scripts/components/share-modal/share-modal-component.jsx, app/scripts/containers/Modal/CreateEmbedWidget.js, app/scripts/pages/explore/explore-map/explore-map-component.jsx, app/styles/_components.scss, app/styles/components/_create-embed-widget.scss
This PR brings support for the embed widgets. The user can embed the map of the NexGDDP tool and the Explore one too.
To test:
- NexGGDP: go to any NexGDDP dataset and create a new widget from the map, it will appear in My Prep.
- Explore: create a map with two layers, click the share button and create the widget. It will also appear in My Prep.
From My Prep, you can get the embed link of the two widgets to test it. If you don't want to create widgets, you can see these two working (you need to run the two apps side-by-side locally):
- NexGDDP: `/embed/embed/a7437274-3089-4026-8aaf-5f0cf06763f1`
- Explore: `/embed/embed/eaf16acb-3ea1-4a3d-b749-4f622ac594aa`
Note tha you won't be able to test properly this PR before these two are merged: resource-watch/prep-manager#65 and …
=> Embed widget support

package-lock.json, package.json
This PR updates [widget-editor](https://www.npmjs.com/package/widget-editor) to v1.0.0 and [vega](https://www.npmjs.com/package/vega) to v3.1.0.
This branch is not ready to be merged until all Prep's widgets have been migrated to Vega 3.
If you want to create some widgets to test it, please include `[Vega 3]` in the title of the chart so we don't have false positives while migrating the existing widgets.
=> [ON HOLD] Widget editor: Update to v1.0.0

app/scripts/components/nexgddp-tool/tool-map/CompareMap.jsx, app/scripts/components/share-modal/share-modal-component.jsx
This PR addresses two bugs around sharing the map of the NexGDDP tool:
- the user wouldn't be able to share the compare map due to a missing import
- the user wouldn't be able to embed any map due to an issue with the share modal's default active tab
[Pivotal task](https://www.pivotaltracker.com/story/show/155198448)
_PS: In the task's comments, I've asked the client further questions regarding other bugs I couldn't replicate._
=> NexGDDP: bugs sharing the map

app/scripts/components/share-modal/share-modal-component.jsx
Towards https://www.pivotaltracker.com/story/show/155199374
Identified bug in explore share modal where unable to navigate through share modal tabs.
=> Explore: Fixes share modal tab navigation

app/scripts/components/Explore/InfoSidebar.jsx, app/scripts/components/dataset-card/dataset-card-component.jsx, app/scripts/pages/explore/explore-dataset-info/explore-dataset-info-component.jsx, static/icons/symbol-defs.hbs
Replace 'learn more' icon to:
*Note:* @davidsingal the alt text for the icon comes from the `<title>` of the svg. This has been changed, but perhaps not the most long term solution if icons are going to be downloaded from icomoon.
=> Explore:  Replace learn more icon

app/scripts/pages/nexgddp-embed/nexgddp-embed-component.jsx
Because the NexGDDP dataset are actually spread into several datasets in the API, when sharing an embed of a NexGDDP visualisation, we would display the name of a specific dataset instead of the one of the "group". By using the metadata's title, we avoid this problem.
[Pivotal task](https://www.pivotaltracker.com/story/show/155978598)
=> Use the dataset's metadata's title for the title of the NexGDDP embeds

app/scripts/components/legend/legend-opacity-selector/legend-opacity-selector-styles.scss
@davidsingal difficult to confirm, as this is not an issue locally. Perhaps something to do with the tooltip package? Have made styling more explicit to out classes.
=> Fix explore map selector hover tooltips layout

app/scripts/pages/explore/explore-location-filter/explore-location-filter-component.jsx, package-lock.json
This PR fixes a bug where the position and zoom of the map would be overridden after their restoration when the app is initialised.
You can test the fix by going to this URL: `/explore?activeDatasets=a9ca92e6-c58c-4527-af45-d698ccb7780f%7C1%7Ctrue%7C0&basemap=default&bbox&boundaries=false&filterQuery=pradesh&labels=none&lat=23.915970370510227&lng=76.03637695312501&location=india&minZoom=3&tab=core_datasets&water=none&zoom=7`. The map should be centered around the layer (you should not see the whole India).
[Pivotal task](https://www.pivotaltracker.com/story/show/158367593)
=> Fix a bug where the position of the map wouldn't be restored correctly

app/scripts/components/user-options/user-options-style.scss, app/styles/components/_nav.scss, app/styles/layout/_header.scss
This PR fixes a bug where the user would be unable to log in because the tooltip would close as soon as the cursor would leave the menu item. The area that triggers the `mouseover` and `mouseout` events has been increased and the tooltip has been brought closer to the menu item.
To test this PR, go to the About and Explore pages and see if you can click the options of the login tooltip.
[Pivotal task](https://www.pivotaltracker.com/story/show/158324867)
=> Fix a bug where the user couldn't login because the tooltip would close

app/scripts/pages/explore/explore-actions.js, app/scripts/pages/explore/explore-dataset-filters/explore-dataset-filters-component.jsx
This PR fixes a bug where the user wouldn't be able to leave the Explore page when clicking the "Learn more" link of a dataset after setting a filter. The user would be redirected right away to Explore once the navigation would be complete because the filters would be reset and they would trigger a URL update.
To test this fix, please follow these steps:
1. Go to the Explore page
2. Select the "All datasets" tab
3. Open the filters by clicking "Filter results"
4. Select the "Asia" geography
5. Click the information button of the first dataset
6. Click the "Learn more" link of the panel
You should correctly navigate to the detail of the dataset.
[Link](https://www.pivotaltracker.com/story/show/158217314)
=> Fix a bug where the user would be unable to navigate away from Explore

app/scripts/pages/dataset/dataset-widget-editor/dataset-widget-editor-component.js, app/scripts/pages/dataset/dataset-widget-editor/index.js
This PR fixes an issue that prevented the user from being able to create a widget from a dataset.
1. Go to http://localhost:5000/dataset/Politcial-Boundaries-GADM-adminitrative-level-1-1490086842541?basemap=default&bbox&boundaries=false&filterQuery=&labels=none&lat=24.367113562651276&lng=-66.97265625000001&location=GLOBAL&minZoom=3&tab=all_datasets&water=none&zoom=3
2. Configure the widget-editor so it displays a chart
3. Click the "Save visualization button"
At this point, a modal should appear.
[Pivotal task](https://www.pivotaltracker.com/story/show/159660563)
=> Bug: unable to create a widget from a dataset page

app/scripts/actions/locatool.js, app/scripts/actions/nexgddptool.js, app/scripts/components/loca-tool/date-range-select/DateRangeSelect.jsx, app/scripts/components/loca-tool/date-range-select/style.scss, app/scripts/components/loca-tool/scenario-select/style.scss, app/scripts/components/loca-tool/temp-resolution-select/style.scss, app/scripts/components/nexgddp-tool/date-range-select/DateRangeSelect.jsx, app/scripts/components/nexgddp-tool/date-range-select/style.scss, app/scripts/components/nexgddp-tool/scenario-select/style.scss, app/scripts/components/nexgddp-tool/temp-resolution-select/style.scss, app/scripts/selectors/locatool.js, app/scripts/selectors/nexgddptool.js
This PR addresses a couple of bugs which prevented the user from using the NexGDDP and Loca tools:
- they wouldn't load
- the date inputs would be broken
1. Go to http://0.0.0.0:5000/dataset/cum_pr_rcp45_decadal
2. Wait a few seconds
The tool should have loaded correctly.
1. Go to http://0.0.0.0:5000/dataset/cum_pr_rcp45_decadal
2. Select a value for the second date range input
There should be a cross icon in the second date range input and if the user clicks on it, it gets emptied.
1. Go to http://0.0.0.0:5000/dataset/cum_pr_rcp45_decadal
2. Open the second date range input
The value of the first date range should be disabled in the second one.
1. Go to http://0.0.0.0:5000/dataset/cum_pr_rcp45_decadal
2. Select a value for the second date range input
3. Select the same value for the …
=> Fix NexGDDP and Loca

app/styles/components/_explore-legend.scss
This PR fixes an issue where the styles of Explore's map legend would apply to the legend of the widget-editor.
1. Go to http://0.0.0.0:5000/dataset/Global-Reservoir-and-Dam-GRanD
2. Select "Map" in the widget-editor
The legend should be correctly placed above the map's credits. Note though that because of another bug, the legend actually doesn't display anything.
[Task (only first part)](https://www.pivotaltracker.com/story/show/159739060)
=> Bug: scope the styles of Explore's map legend

package.json, yarn.lock
This PR fixes an issue where the legend of the [widget-editor](https://github.com/resource-watch/widget-editor) wouldn't work properly.
1. Go to localhost:5000/dataset/Global-Reservoir-and-Dam-GRanD
2. Select the "Map" visualisation in the widget-editor
3. Click the toggle button of the legend
You should be able to see the content of the legend.
[Task (second part)](https://www.pivotaltracker.com/story/show/159739060)
=> Bug: widget-editor's legend not working

app/scripts/components/Modal/CreateEmbedWidget.jsx
This PR fixes an issue where the user would be unable to create a widget from the Explore map.
1. Log in
2. Go to http://localhost:5000/explore?activeDatasets=eadf93a6-58e7-4482-89d6-c9832d270a87%7C1%7Ctrue%7C0&basemap=default&bbox&boundaries=false&filterQuery=&labels=none&lat=24.44714958973082&lng=-66.97265625000001&location=GLOBAL&minZoom=3&tab=core_datasets&water=none&zoom=3
3. Click the share button of the map
4. Select the "Widget" tab in the modal
5. Give the widget a title and click "Create"
You shouldn't see any error in the modal or the console.
Not tracked.
=> Bug: unable to create a widget from the Explore's map

app/scripts/pages/explore/explore-embed-component.jsx
This PR fixes a bug where the user can navigate away from the main visualisation of an Explore embed.
1. Go to http://localhost:5000/embed/explore/?activeDatasets=eadf93a6-58e7-4482-89d6-c9832d270a87%7C1%7Ctrue%7C0&basemap=default&bbox&boundaries=false&filterQuery=&labels=dark&lat=24.44714958973082&lng=-66.97265625000001&location=GLOBAL&minZoom=3&tab=core_datasets&water=none&zoom=3
2. Click the info button of the legend
3. Click "Learn more" in the sidebar
A new tab should open with the details of the dataset (instead of in the current tab).
Part of [this task](https://www.pivotaltracker.com/story/show/159172219).
=> Bug: user can navigate away from Explore embed

app/scripts/modules/user/index.js
This PR fixes an issue where some users reported being unable to login because the tooltip wouldn't open.
1. Go to http://localhost:5000/ and log out
2. Open the developer tools and simulate an iPad in landscape mode
3. Reload the page
You should be able to open the login tooltip by hovering the account icon and by clicking on one of the providers.
[Task](https://www.pivotaltracker.com/story/show/159120484)
=> Bug: users unable to login because of the tooltip

app/scripts/actions/datasets.js, app/scripts/pages/nexgddp-embed/nexgddp-embed-component.jsx, package.json, yarn.lock
This PR fixes an issue where some NexGDDP widgets might fail to load because the project used two different serializer that would return different results.
1. Open http://localhost:5000/embed/nexgddp/xpr_rcp45_decadal?zoom=6&lat=23.059516273509317&lng=78.4423828125&mapMode=side-by-side&graphMode=timeseries&scenario=rcp45&tempResolution=decadal&range1=2011-01-01T00%3A00%3A00.000Z&range2=2041-01-01T00%3A00%3A00.000Z&labels=light&boundaries=true&render=map
The layers should load correctly.
Part of [this task](https://www.pivotaltracker.com/story/show/159829264).
=> Bug: NexGDDP widgets might fail to load

app/styles/components/_info-sidebar.scss
This PR fixes an issue where the user would be unable to hide the sidebar of the Explore embeds once opened because the close button would be outside the viewport.
On this image, you can see the fix lets the user close the sidebar (right):
</p>
1. Open http://localhost:3000/embed/explore/?activeDatasets=d597c392-086d-4e4f-b33b-4d8f520bb547%7C1%7Ctrue%7C2&basemap=light&bbox&boundaries=true&filterQuery=irrigat&labels=dark&lat=23.926013645952843&lng=77.96997204422954&location=IND&minZoom=3&tab=all_datasets&water=none&zoom=6
2. Click the info button of the legend
You should be able to close the sidebar.
Part of [this task](https://www.pivotaltracker.com/story/show/159829264).
=> Bug: unable to hide sidebar in Explore embeds

app/scripts/components/Dashboards/index.jsx
This PR displays the author of the dashboards.
</p>
1. Add the param `published=all` to [this query](https://github.com/resource-watch/prep-app/blob/2865db5421a2270bb20e88e465e61ed7b4d74a45/app/scripts/actions/dashboards.js#L14)
2. Go to http://localhost:5000/dashboards
The first dashboard, Test Clément - partner, contains a logo and the name of the author.
Part of [this task](https://www.pivotaltracker.com/story/show/158256199).
=> Display the author of the dashboards
