- app/src/components/pages/HomePage.jsx
homogeneous spelling  and puntuation
> applied text changes for PREP

- app/scripts/components/Dashboards/DashboardDetailInsights.jsx
- app/scripts/components/Dashboards/DashboardDetailTools.jsx
Add attribution info to insights and tools cards.
> Attribution added to insights & tools cards

- app/scripts/components/Dashboards/NavTab.jsx
- app/scripts/components/Modal/Modal.jsx
- app/scripts/components/Modal/ShareModal.jsx
- app/scripts/components/ToolbarActions/index.jsx
- app/styles/components/_modal.scss
- app/styles/components/_nav-tab.scss
> Share styles fix

- app/scripts/components/Explore/ExploreSidebar.jsx
- app/styles/components/_explore-sidebar.scss
- A new title _-cdi-tag_ scss style.
- Behavior that changes the dataset title class from: _"title"_ to: _"title -cdi-tag"_ if it contains a tag called CDI.
> Adds a CDI tag to all datasets that are tagged as CDI

- app/scripts/components/Partners/index.jsx
- Partners descriptions removed.
> Partners descriptions removed

- app/scripts/components/Explore/FilterTabs.jsx
This pull request adds the following:
- New functionality where a second click on the same filter menu option closes the dropdown.
> Second click on filter menu closes dropdown

- app/scripts/components/Map/SimpleMap.jsx
This pull request disables the scroll zoom on the simple map component.
> disables scroll zoom on simple map component

- app/scripts/components/Button/Button.js
- app/scripts/components/Modal/WelcomeModal.jsx
- app/scripts/components/ToolbarActions/index.jsx
- app/styles/components/_button.scss
- app/styles/components/_toolbar-actions.scss
- Changes to the button css, a new sub class _-alternative_ that uses the secondary yellow, preferable for white backgrounds.
- Changes to the share button to make it more visible.
> changes share button to a more visible version

- app/scripts/components/Explore/ExploreMap.jsx
This Pull request contains:
- Changes to the **Explorer Map** component that allows the user to set the order in which the layers are placed in to of each other.
- Set the layer.option.pane value to _tilePane_ on all layers in order to place them in the same html block.
- If the layer doesn't have a _setZIndex_ method, locates the layer's parent with the _map.getPane_ method.
> Fix issue where the overlay image layers werent able to change position

- app/scripts/components/FAQ/index.jsx
Edits to FAQ text to be less US-centric
> faq text edits

- app/scripts/actions/datasets.js
- app/scripts/reducers/datasets.js
This pull request fixes the ESLint issues.
> ESlint fixes

- app/scripts/actions/datasets.js
Fixed bug where the layers got lost if you shared the URL
> layers sharing bug fixed

- app/scripts/components/Partnership/Articles/JoinPartnership.jsx
- app/scripts/components/Partnership/index.jsx
- New function in the partnership component to emulate the html anchor functionality.
> Fixed html anchors to point to the correct content

- app/scripts/actions/datasets.js
- Change in a for-loop to be able to include the 1st element in the default dataset layers array.
> Fixes issue where the 1st dataset could not be loaded as a default.

- app/scripts/components/Cards/EmbedCard.jsx
- app/scripts/components/Cards/MapCard.jsx
- app/scripts/components/Dashboards/DashboardDetailIndicators.jsx
- Fixes to the dashboard embed and map cards: they now include a link to the dataset.
> fixes broken link at dashboards mapCard and embedCard

- config/webpack.config.js
- package.json
> Fix to compatibility problems with IE 11

- app/scripts/components/Partnership/Articles/JoinPartnership.jsx
Replaced the mail chimp form with a link to a Google form for new partner requests.
> new partner form

- app/scripts/components/PartnerDetail/index.jsx
- app/scripts/components/Partners/index.jsx
- app/styles/components/_partners.scss
* Add partner link at partned detail page
> Add partner link @ partner detail page

- app/scripts/components/Cards/ChartCard.jsx
- app/styles/components/_content-card.scss
> Center home widgets icons

- index.html
> Fixes label typo

- app/scripts/components/Explore/ExploreLegend.jsx
Closes https://www.pivotaltracker.com/story/show/153249352
e.g.: *Projected Average Temperature Change -- Higher Emissions (2041-2070) -- U.S.* **=>** *Projected Average Temperature Change -- U.S. (Midwest)*
> Amend explore map legend title to layer name

- app/scripts/components/Dataset/index.jsx
- app/scripts/components/Root/index.jsx
- app/scripts/index.jsx
- app/styles/_components.scss
- app/styles/components/_widget-editor.scss
- config/webpack/shared.js
- package-lock.json
- package.json
- yarn.lock
> 💥 New editor #micdrop

- app/scripts/components/Dataset/index.jsx
- app/scripts/components/Explore/DatasetItem.jsx
- app/scripts/containers/Dataset/index.js
- app/scripts/routes.jsx
- app/styles/components/_dataset-item.scss
Closes https://www.pivotaltracker.com/story/show/153358190
> Link dataset details from explore

- app/scripts/components/Explore/DatasetItem.jsx
Closes https://www.pivotaltracker.com/story/show/153249352
> Fix dataset item to use layer name

- app/styles/components/_explore-map.scss
- app/styles/layout/_header.scss
Closes https://www.pivotaltracker.com/story/show/153398832
> Explore page styling updates

- app/scripts/components/user-options/user-options-style.scss
- app/scripts/components/user/user-style.scss
- app/styles/layout/_header.scss
Fixes logged in hover state for explore page where user is unable to select menu items
> Fix explore user menu bug for logged in

- app/scripts/actions/datasets.js
- app/scripts/actions/info-sidebar.js
- app/scripts/components/Dashboards/RelatedDatasets.jsx
- app/scripts/components/Dataset/index.jsx
- app/scripts/components/Explore/DatasetItem.jsx
- app/scripts/components/Explore/ExploreLegend.jsx
- app/scripts/components/Explore/InfoSidebar.jsx
- app/scripts/components/ui/DatasetsList.jsx
- app/scripts/containers/Dashboards/RelatedDatasets.js
- app/scripts/containers/Dataset/index.js
- app/scripts/containers/Explore/ExploreLegend.js
- app/scripts/containers/Explore/ExploreSidebar.js
- app/scripts/containers/Explore/InfoSidebar.js
- app/scripts/reducers/datasets.js
- app/scripts/reducers/info-sidebar.js
- app/scripts/routes.jsx
Closes https://www.pivotaltracker.com/story/show/153366492
Closes related bug https://www.pivotaltracker.com/story/show/153564102
> Update dataset urls to use slug rather than id

- app/scripts/components/Explore/DatasetItem.jsx
Closes https://www.pivotaltracker.com/story/show/153249352
> Update dataset item title to reflect dataset name

- app/scripts/actions/datasets.js
- app/scripts/reducers/datasets.js
This is a regression from PR  #107.
> Fix a bug that prevent the user to access any dataset

- app/scripts/components/Dashboards/index.jsx
Minor text edits to the intro text on the Dashboards page
> Update dashboard text

- app/scripts/components/Insights/index.jsx
Minor text updates to intro text on Stories page
> update stories intro text

- app/scripts/components/Resources/index.jsx
Added header similar to Dashboards/Stories pages and made minor text edits to intro text
> resources update text

- index.html
Add launch date to coming soon page
> Add launch date to coming soon page

- app/scripts/components/Root/index.jsx
Updated platform title to PREPdata
> Update title to PREPdata

- app/scripts/components/Modal/WelcomeModal.jsx
Minor text updates to welcome modal
> Modal test update

- app/scripts/components/ToolbarActions/index.jsx
- app/styles/components/_widget-editor.scss
- app/styles/components/ui/_icon.scss
Some amendments to the dataset detail page
> dataset details styles amendments

- app/scripts/components/Home/index.jsx
Updated "Go to Resources" to /resources; updated "Learn More" to /about
> Updating button links

- app/scripts/components/Insights/Customs/Ethiopia/index.jsx
https://climateserv.servirglobal.net
> Fix climateserv link

- app/scripts/components/Partners/index.jsx
Since not all have descriptions
> Remove partner descriptions from partner page

- app/scripts/actions/partners.js
- app/scripts/components/Slider/PartnersSlider.jsx
- app/styles/components/_partners-slider.scss
Task: https://www.pivotaltracker.com/story/show/154135263
> Add arrows to desktop partner carousel

- app/scripts/components/Home/index.jsx
- app/scripts/components/Slider/PartnersSlider.jsx
Task: https://www.pivotaltracker.com/story/show/154135263
> Revert arrow slider for all partners sliders

- app/scripts/pages/about/about-page-component.jsx
Sorry, a few more tiny changes. Thanks!!
> about-text-updates-v2

- app/scripts/pages/explore/explore-component.jsx
- app/styles/components/ui/_datasets-list.scss
Task: https://www.pivotaltracker.com/story/show/154215841
> Adds suggest dataset button to sidebar

- app/scripts/helpers/graph-service.js
- app/scripts/pages/explore/explore-actions.js
- app/scripts/pages/explore/explore-dataset-filters/data/periods.json
- app/scripts/pages/explore/explore-dataset-filters/explore-dataset-filters-constants.js
- app/scripts/pages/explore/explore-datasets-list/explore-datasets-list-selector.js
- app/scripts/services/dataset-filter-service.js
Task: https://www.pivotaltracker.com/story/show/153742816
> Adds period filter

- app/scripts/pages/explore/explore-dataset-info/explore-dataset-info-component.jsx
- app/styles/components/_info-sidebar.scss
> Brings back dataset tags in sidebar info

- app/scripts/actions/nexgddptool.js
- app/scripts/components/Dataset/index.jsx
- app/scripts/components/legend/legend-types/legend-gradient/legend-gradient.scss
- app/scripts/components/nexgddp-tool/NexGDDPTool.jsx
- app/scripts/components/nexgddp-tool/tool-chart/TimeseriesChart.jsx
- app/scripts/components/nexgddp-tool/tool-map/CompareMap.jsx
- app/scripts/components/nexgddp-tool/tool-map/DifferenceMap.jsx
- app/scripts/components/nexgddp-tool/tool-map/SimpleMap.jsx
- app/scripts/components/nexgddp-tool/tool-map/ToggleMap.jsx
- app/scripts/components/nexgddp-tool/tool-map/style.scss
- app/scripts/reducers/nexgddptool.js
- app/scripts/selectors/nexgddptool.js
- package-lock.json
This PR adds new features to the NexGDDP tool:
* Y axis for the graph
* Legend for the map
* Use of the new API
In addition, a bug where the boundaries and labels layers would be hidden behind the "data" layer has been fixed.
You can test the PR with this dataset: `/dataset/tasavg_rcp45_decadal`.
[Pivotal task 1](https://www.pivotaltracker.com/story/show/154171133)
[Pivotal task 2](https://www.pivotaltracker.com/story/show/154171151)
[Pivotal task 3](https://www.pivotaltracker.com/story/show/154211460)
> Update of the NexGDDP tool

- app/styles/layout/_header.scss
Closes https://www.pivotaltracker.com/story/show/154215794
**Old:**
**New:**
> Remove beta text from main logo

- app/scripts/pages/about/about-page-component.jsx
it was missing a space, my mistake!
> about-text-update

- app/scripts/pages/resources/resources-page-component.jsx
removed first header to avoid repetition
> resource-text-update

- app/scripts/components/App/index.jsx
- app/scripts/components/Create/index.jsx
- app/scripts/components/Dashboards/DashboardDetailInsights.jsx
- app/scripts/components/Insights/InsightDetail.jsx
- app/scripts/components/Insights/index.jsx
- app/scripts/components/Navigation/MainNav.jsx
- app/scripts/components/SummaryCards/index.jsx
- app/scripts/metadata.json
- app/scripts/routes.jsx
Closes https://www.pivotaltracker.com/story/show/154215682
> Change path from insights to stories reflecting in content

- app/scripts/components/nexgddp-tool/location-search/LocationSearch.jsx
- app/scripts/components/nexgddp-tool/location-search/style.scss
- app/scripts/components/nexgddp-tool/tool-map/ToggleMap.jsx
Related to https://www.pivotaltracker.com/story/show/154279165. 
- updated the styling of the location search input
- fixed adding a marker in marker mode for the Toggle map
> Update gddp geosuggest styling

- app/scripts/pages/explore/explore-component.jsx
- app/styles/components/_explore-map.scss
> Adds collapse option for explore sidebar

- app/scripts/components/Root/index.jsx
Adding User Report script (except `/embeds`):
> Add User Report script to all pages except embeds

- .babelrc
- app/scripts/components/Spinner/index.js
- app/scripts/components/Spinner/spinner-component.jsx
- app/scripts/components/Spinner/spinner-styles.scss
- app/scripts/components/collections-panel/collections-panel-component.js
- app/scripts/components/collections-panel/collections-panel-constants.js
- app/scripts/components/collections-panel/collections-panel-helpers.js
- app/scripts/components/collections-panel/collections-panel-item/collections-panel-item-component.js
- app/scripts/components/collections-panel/collections-panel-selectors.js
- app/scripts/components/collections-panel/collections-panel-styles.scss
- app/scripts/components/collections-panel/index.js
- app/scripts/components/user/user-actions.js
- app/scripts/components/user/user-initial-state.js
- app/scripts/components/user/user-reducer.js
- app/scripts/components/user/user.js
- app/scripts/pages/explore/explore-component.jsx
- app/scripts/pages/explore/explore-dataset-info/explore-dataset-info-component.jsx
- app/scripts/pages/explore/explore-dataset-info/index.js
- app/scripts/services/collections-service.js
- app/scripts/services/favourites-service.js
- app/styles/_components.scss
- app/styles/_settings.scss
- app/styles/components/_info-sidebar.scss
- app/styles/components/_rc-tooltip.scss
- package-lock.json
- package.json
Task: https://www.pivotaltracker.com/story/show/153632342
> Implementing collections

- app/scripts/components/nexgddp-tool/location-search/LocationSearch.jsx
https://www.pivotaltracker.com/story/show/154561164
> NexGDDP: search, zoom and pan

- app/scripts/components/Dashboards/index.jsx
- app/scripts/components/Form/index.jsx
- app/scripts/components/Home/index.jsx
- app/scripts/components/Insights/index.jsx
- app/scripts/components/Modal/ShareUrl.jsx
- app/scripts/components/basemap-control/basemap-control-component.jsx
- app/scripts/components/dataset-card/dataset-card-component.jsx
- app/scripts/components/legend/legend-actions/legend-actions-component.jsx
- app/scripts/components/share-control/share-control-component.jsx
- app/scripts/components/user-options/user-options-component.jsx
- app/scripts/helpers/analytics.js
- app/scripts/index.jsx
- app/scripts/pages/about/about-page-component.jsx
- app/scripts/pages/explore/explore-component.jsx
- app/scripts/pages/explore/explore-dataset-filters/explore-dataset-filters-component.jsx
- app/scripts/pages/explore/explore-dataset-info/explore-dataset-info-component.jsx
- app/scripts/pages/explore/explore-location-filter/explore-location-filter-component.jsx
- app/scripts/pages/explore/index.js
- package-lock.json
- package.json
This PR adds the analytics events to the app. I'll make a complementary PR to [prep-manager](https://github.com/resource-watch/prep-manager).
@mbarrenechea Do you know if we need to set the GA key for the production site or its already done?
[Pivotal task](https://www.pivotaltracker.com/story/show/154358805)
> Analytics events

- app/scripts/components/Insights/Customs/Ethiopia/index.jsx
- app/scripts/components/Insights/InsightDetail.jsx
- app/scripts/components/Modal/ShareModal.jsx
- app/scripts/components/Modal/ShareUrl.jsx
- app/scripts/components/SectionIntro/index.jsx
- app/scripts/components/Thumbnails/Thumbnail.jsx
- app/scripts/components/ToolbarActions/index.jsx
- app/scripts/components/share-control/share-control-component.jsx
- app/scripts/components/share-modal/index.js
- app/scripts/components/share-modal/share-modal-actions.js
- app/scripts/components/share-modal/share-modal-component.jsx
- app/scripts/components/share-modal/share-modal-reducers.js
- app/scripts/pages/resources/resource-item-component.jsx
This PR adds analytics events for Stories and Resources.
[Pivotal task](https://www.pivotaltracker.com/story/show/154358805)
> New analytics events for Stories and Resources

- app/scripts/pages/about/about-page-component.jsx
Removed "HERE" and tried to add a space between "and" and "Technical WG"
> about-page-text-edits

- app/scripts/pages/explore/explore-dataset-info/explore-dataset-info-component.jsx
- package-lock.json
It just removes the areas section inside the dataset info
> Explore: Remove areas from dataset info

- app/scripts/components/Modal/ShareUrl.jsx
This PR prevents iframes urls from being shorted. 
https://www.pivotaltracker.com/story/show/154852418
> Prevent shorten from iframe urls

- app/scripts/pages/explore/explore-actions.js
Closes https://www.pivotaltracker.com/story/show/154762397
> Explore: Fix clear filters of original filter data after page reload

- app/scripts/components/Button/arrow-button-component.jsx
- app/scripts/components/Slider/PartnersSlider.jsx
Closes https://www.pivotaltracker.com/story/show/154924022
> Home:  Fix partner carousel button visibility on scroll

- app/scripts/routes.jsx
**Part 1:** Closes https://www.pivotaltracker.com/story/show/154367331
> Prep App - Fix/cross domain logout

- app/scripts/pages/explore/explore-dataset-filters/explore-dataset-filters-component.jsx
Closes https://www.pivotaltracker.com/story/show/154336250
> Explore: clear filters on unmount of filters component

- app/scripts/components/nexgddp-tool/tool-chart/TimeseriesChart.jsx
This PR updates the template of the NexGDDP chart to user Vega 3.
Most of the work if from @aagm (commits 1 and 3). Her initial PR (#227) had to be rebased.
> NexGDDP: new Vega 3 chart

- app/scripts/components/Insights/Customs/Ethiopia/jsons/chirps.json
- app/scripts/components/Insights/Customs/Ethiopia/jsons/seasonal.json
- app/scripts/components/Insights/Customs/Ethiopia/jsons/somali-seasonal.json
- app/scripts/components/Insights/Customs/Ethiopia/jsons/tigray-seasonal.json
- app/scripts/components/Insights/Customs/Ethiopia/jsons/tigray.json
> new vega-3 definition for ethiopia insight

- app/scripts/components/legend/legend-actions/legend-actions-component.jsx
- app/scripts/components/legend/legend-bounding-selector/index.js
- app/scripts/components/legend/legend-bounding-selector/legend-bounding-selector-component.jsx
- app/scripts/components/legend/legend-bounding-selector/legend-bounding-selector-styles.scss
- app/scripts/components/legend/legend-opacity-selector/legend-opacity-selector-component.jsx
**Closes:** https://www.pivotaltracker.com/story/show/155399809
> Explore: Add tooltip to zoom to bounds legend item button

- app/styles/components/_widget-editor.scss
Closes https://www.pivotaltracker.com/story/show/155624452
**Fixes:**
- Vertical center compressed button text
- Fix layout of column box content
> Dataset: Fix widget editor button and column box styling

- app/scripts/components/Modal/CreateEmbedWidget.jsx
Amend loader style to be transparent:
> Explore: Transparent loader for create widget

- app/scripts/components/Root/index.jsx
Reinstates user feedback script. @davidsingal the code was commented out, was there a reason for that?
> Reinstate user feedback script

- app/scripts/components/user-options/user-options-component.jsx
Towards https://www.pivotaltracker.com/story/show/155809331 for `prep-app`.
> Fix applications social media login property

- app/scripts/components/dataset-card/dataset-card-component.jsx
- app/styles/components/_dataset-item.scss
Closes https://www.pivotaltracker.com/story/show/155783162
> Explore: Amend dataset link to icon rather than title

- app/scripts/components/legend/legend-opacity-selector/legend-opacity-selector-styles.scss
- app/scripts/components/search-control/index.js
- app/scripts/components/search-control/search-control-component.jsx
- app/scripts/pages/explore/explore-map/explore-map-component.jsx
- app/scripts/pages/explore/location-search/index.js
- app/scripts/pages/explore/location-search/location-search-component.jsx
- app/scripts/pages/explore/location-search/location-search-styles.scss
- app/styles/_components.scss
- app/styles/components/_basemap-control.scss
- app/styles/components/_explore-map.scss
- app/styles/components/_search-control.scss
Towards https://www.pivotaltracker.com/story/show/153826007
**Todo**: 
**Help wanted for:**
*Note:* Consider creating a task for a global `LocationSearch` component.
> Explore: Add location search component to explore map

- app/scripts/components/map-vis/map-vis-component.jsx
- app/scripts/pages/explore/explore-map/explore-map-component.jsx
Closes https://www.pivotaltracker.com/story/show/153826007
> Explore: Set map view on location search

- app/scripts/reducers/nexgddptool.js
Closes https://www.pivotaltracker.com/story/show/155978665
> Nex GDDP: Enable country labels by default

- app/scripts/components/Tooltip/ShareNexgddpTooltip.jsx
- app/scripts/components/share-control/share-control-component.jsx
- app/scripts/pages/explore/explore-map/explore-map-component.jsx
- package-lock.json
This PR fixes an issue where the share modal wouldn't have the first tab selected by default when opening it. This would cause, for example, the modal to open with no content while there would be only one tab available (case of the NexGDDP visualisations).
[Pivotal task](https://www.pivotaltracker.com/n/projects/1598595/stories/155198448)
> Share modal: Fix a regression from #235

- app/scripts/components/Tooltip/ShareLocaTooltip.jsx
- app/scripts/components/loca-tool/tool-map/SimpleMap.jsx
Closes https://www.pivotaltracker.com/story/show/157160646
> Loca Detail: Fix save widget

- app/scripts/components/Dashboards/index.jsx
Closes: https://www.pivotaltracker.com/n/projects/1598595/stories/155288894
Add action to create own dashboard:
> Dashboards: Add link to myprep

- app/scripts/components/App/index.jsx
- app/scripts/components/Navigation/SecondaryNav.jsx
- app/scripts/components/privacy-policy/index.jsx
- app/scripts/components/terms-of-service/index.jsx
- app/scripts/metadata.json
- app/scripts/routes.jsx
- app/styles/_components.scss
- app/styles/components/_terms-list.scss
Closes https://www.pivotaltracker.com/story/show/157186765
> Add privacy policy and terms of service pages

- app/scripts/pages/explore-embed/explore-map/index.js
Closes: https://www.pivotaltracker.com/story/show/157355033
> Embed map: fix map boundaries and zoom

- app/scripts/pages/explore/explore-dataset-filters/explore-dataset-filters-component.jsx
Closes: https://www.pivotaltracker.com/story/show/157356893
> Explore: Make global filter first option

- app/scripts/components/collections-panel/collections-panel-component.js
- package-lock.json
This PR's only change is to send an analytics event whenever a user favourites a dataset on the Explore page.
[Pivotal task](https://www.pivotaltracker.com/story/show/156799958)
> Analytics event when favouriting a dataset

- app/scripts/actions/dashboards.js
- app/scripts/actions/insights.js
- app/scripts/modules/partners/partners-actions.js
Added env params to dashboard, insights and partners requests.
> added env for dashboards insights and partners

- app/scripts/actions/datasets.js
- app/scripts/actions/exploremap.js
- app/scripts/actions/layers.js
- app/scripts/actions/locatool.js
- app/scripts/actions/nexgddptool.js
- app/scripts/actions/widgets.js
- app/scripts/components/legend/legend-loca-toolbar/legend-loca-toolbar-component.jsx
- app/scripts/components/legend/legend-nexgddp-toolbar/legend-nexgddp-toolbar-component.jsx
- app/scripts/pages/explore-embed/explore-embed-actions.js
- app/scripts/pages/explore/explore-actions.js
- app/scripts/services/favourites-service.js
- app/scripts/services/graph-service.js
Added header `Upgrade-Insecure-Requests: 1` to all API requests.
> added upgrade inscure requests to all requests

- app/scripts/pages/explore/explore-location-filter/explore-location-filter-data.js
Changed "US" to "United States"
> spell_out_united_states

- app/scripts/pages/explore/core-datasets-list/core-datasets-list-data.json
Added a fourth category (physical features) and additional sub-categories, along with API IDs for relevant global, US, and India datasets.
@davidsingal
> adding-new-core-topics-and-subtopics

- app/scripts/components/dataset-card/dataset-card-component.jsx
- app/scripts/pages/explore/core-datasets-list/core-datasets-list-component.jsx
- app/scripts/pages/explore/explore-country-component.jsx
- app/scripts/pages/explore/explore-dataset-info/explore-dataset-info-component.jsx
- app/scripts/pages/explore/explore-datasets-list/explore-datasets-list-component.jsx
This PR makes sure that the links found in the country explore page open in a new tab as this page will be embedded.
You can test this PR by:
- going to  `/explore/ind` and checking if the links open in a new page
- going to  `/explore` and checking that the links open in the same page (except the ones of the description of the datasets)
[Pivotal task](https://www.pivotaltracker.com/story/show/159137152)
> Make sure the links of the country explore page open in a new tab

- app/scripts/pages/explore/core-datasets-list/core-datasets-list-data.json
@davidsingal flagging this for you - added a few new datasets to the "core" list (in advance of the backoffice updates being pushed to production)
> add-uttarakhand-ag-core-datasets

- app/scripts/actions/locatool.js
- app/scripts/actions/nexgddptool.js
- app/scripts/components/Tooltip/ShareNexgddpTooltip.jsx
- app/scripts/components/loca-tool/date-range-select/DateRangeSelect.jsx
- app/scripts/components/loca-tool/date-range-select/style.scss
- app/scripts/components/loca-tool/scenario-select/style.scss
- app/scripts/components/loca-tool/temp-resolution-select/style.scss
- app/scripts/components/nexgddp-tool/date-range-select/DateRangeSelect.jsx
- app/scripts/components/nexgddp-tool/date-range-select/style.scss
- app/scripts/components/nexgddp-tool/scenario-select/style.scss
- app/scripts/components/nexgddp-tool/temp-resolution-select/style.scss
- app/scripts/selectors/locatool.js
- app/scripts/selectors/nexgddptool.js
**⚠️ Merge after #272. This PR should contain only one commit.**
This PR fixes a bug where the user would be able to see the "Save widget" button of the NexGDDP and Loca tools without being logged in.
1. Go to http://localhost:5000/dataset/cum_pr_rcp45_decadal
2. Click the share button of the map of the NexGDPP tool
If you're logged in, you should see the "Save widget" option. If not, it should be hidden.
Not tracked.
> Bug: saving a NexGDDP/Loca widget

- app/scripts/pages/explore/explore-map/explore-map-component.jsx
- app/scripts/pages/explore/explore-map/explore-map-selector.js
Added styles for enabled, focus and default states in the icons for the legend.
> configured legend icons styles

- app/scripts/modules/auth/index.js
This PR fixes a bug where the user would be unable to log in.
1. Go to http://localhost:5000
2. Hover the login icon from the navigation menu and log in with one of the options
You should be redirected to the homepage and the menu should display your profile image.
Not tracked.
> Bug: user unable to log in

- app/scripts/pages/explore/core-datasets-list/core-datasets-list-constants.js
precipitations -> precipitation
> precipitation

- app/scripts/components/Explore/index.jsx
- app/scripts/components/Insights/Customs/Ethiopia/index.jsx
- app/scripts/components/Insights/InsightDetail.jsx
- app/scripts/layout/app/index.jsx
- app/scripts/pages/explore/explore-embed-component.jsx
- app/scripts/pages/loca-embed/nexgddp-embed-component.jsx
- app/scripts/pages/nexgddp-embed/nexgddp-embed-component.jsx
- app/styles/_base.scss
- app/styles/_settings.scss
- app/styles/components/_button.scss
- app/styles/components/_card.scss
- app/styles/components/_climate-change.scss
- app/styles/components/_content-card.scss
- app/styles/components/_explore-sidebar.scss
- app/styles/components/_form.scss
- app/styles/components/_loading-spinner.scss
- app/styles/components/_modal.scss
- app/styles/components/_nav.scss
- app/styles/components/_section-intro.scss
- app/styles/components/_thumbnail.scss
- app/styles/components/_toolbar-actions.scss
- app/styles/components/ui/_icon.scss
- app/styles/layout/_main.scss
This PR removes the themes and their colours from the app.
1. Go to every page and check everything looks fine
[Task](https://www.pivotaltracker.com/story/show/159765577)
> Remove the theme colours from the app

- app/index.hbs
- app/scripts/pages/explore/location-search/location-search-component.jsx
Fixes a regression added in the Google Maps API.
> Fixes location search

- app/scripts/components/Root/index.jsx
- app/scripts/components/gdpr-banner/component.js
- app/scripts/components/gdpr-banner/helpers.js
- app/scripts/components/gdpr-banner/index.js
- app/scripts/routes.jsx
- app/styles/_components.scss
- app/styles/components/_gdpr-banner.scss
This PR adds a GDPR banner to all pages in the platform. We use localStorage so that the banner is hidden once the user accepts the terms.
> GDPR implemented

- README.md
Wouldn't be surprised if I missed some dependency, sorry.
> Adds dependencies to other Microservices to README
